//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Answer
    {
        public int AnswerID { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string AnswerContent { get; set; }
        public int QuestionID { get; set; }
        public bool IsRight { get; set; }
        public Nullable<int> Score { get; set; }
    
        public virtual Question Question { get; set; }
    }
}
