//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.AnswerChilds = new HashSet<Answer>();
        }
    
        public int AnswerID { get; set; }
        public string AnswerContent { get; set; }
        public int QuestionID { get; set; }
        public bool IsRight { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<int> SerialOrder { get; set; }
        public Nullable<int> DependencyAnswerID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual ICollection<Answer> AnswerChilds { get; set; }
        public virtual Answer AnswerParent { get; set; }
    }
}
