//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Question
    {
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.UserInTestDetails = new HashSet<UserInTestDetail>();
            this.Tags = new HashSet<Tag>();
        }
    
        public int QuestionID { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string QuestionTitle { get; set; }
        public int TestID { get; set; }
        public int QuestionTypeID { get; set; }
        public string ImageUrl { get; set; }

        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string TextDescription { get; set; }
        public decimal QuestionScore { get; set; }
        public Nullable<int> SerialOrder { get; set; }
        public string LabelOrder { get; set; }
        public Nullable<int> NoneChoiceScore { get; set; }
    
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual QuestionType QuestionType { get; set; }
        public virtual Test Test { get; set; }
        public virtual ICollection<UserInTestDetail> UserInTestDetails { get; set; }
        public virtual ICollection<Tag> Tags { get; set; }
    }
}
