//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingConfigDetail
    {
        public int SettingConfigDetailID { get; set; }
        public int SettingConfigID { get; set; }
        public int SettingTypeID { get; set; }
        public Nullable<int> NumberValue { get; set; }
        public string TextValue { get; set; }
        public bool IsActive { get; set; }
    
        public virtual SettingConfig SettingConfig { get; set; }
        public virtual SettingType SettingType { get; set; }
    }
}
