//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TagInRelationShip
    {
        public int TagInRelationID { get; set; }
        public Nullable<int> TagID { get; set; }
        public Nullable<int> TestID { get; set; }
        public Nullable<int> QuestionID { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Tag Tag { get; set; }
        public virtual Test Test { get; set; }
    }
}
