//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInTest
    {
        public UserInTest()
        {
            this.UserInTestDetails = new HashSet<UserInTestDetail>();
        }
    
        public int UserInTestID { get; set; }
        public int TestID { get; set; }
        public int UserID { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<System.DateTime> TestTakenDate { get; set; }
        public int NumberOfAttend { get; set; }
    
        public virtual Test Test { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserInTestDetail> UserInTestDetails { get; set; }
    }
}
