//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingConfig
    {
        public SettingConfig()
        {
            this.Tests = new HashSet<Test>();
            this.SettingTypes = new HashSet<SettingType>();
        }
    
        public int SettingConfigID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Test> Tests { get; set; }
        public virtual ICollection<SettingType> SettingTypes { get; set; }
    }
}
