//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public Tag()
        {
            this.TagInQuestions = new HashSet<TagInQuestion>();
            this.TagInTests = new HashSet<TagInTest>();
        }
    
        public int TagID { get; set; }
        public string TagName { get; set; }
    
        public virtual ICollection<TagInQuestion> TagInQuestions { get; set; }
        public virtual ICollection<TagInTest> TagInTests { get; set; }
    }
}
