//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.Invitations = new HashSet<Invitation>();
            this.Questions = new HashSet<Question>();
            this.TagInRelationShips = new HashSet<TagInRelationShip>();
            this.TestSettings = new HashSet<TestSetting>();
            this.UserInTests = new HashSet<UserInTest>();
        }
    
        public int TestID { get; set; }
        public string TestTitle { get; set; }
        public int UserID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> TestTime { get; set; }
    
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<TagInRelationShip> TagInRelationShips { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<TestSetting> TestSettings { get; set; }
        public virtual ICollection<UserInTest> UserInTests { get; set; }
    }
}
