//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OATS_Capstone.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Test
    {
        public Test()
        {
            this.FeedBacks = new HashSet<FeedBack>();
            this.Invitations = new HashSet<Invitation>();
            this.Questions = new HashSet<Question>();
            this.TagInTests = new HashSet<TagInTest>();
            this.UserInTests = new HashSet<UserInTest>();
        }
    
        public int TestID { get; set; }
        public string TestTitle { get; set; }
        public int CreatedUserID { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public Nullable<System.DateTime> EndDateTime { get; set; }
        public Nullable<int> SettingConfigID { get; set; }
        public bool IsActive { get; set; }
        public string Introduction { get; set; }
        public bool IsRunning { get; set; }
        public bool IsComplete { get; set; }
    
        public virtual ICollection<FeedBack> FeedBacks { get; set; }
        public virtual ICollection<Invitation> Invitations { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual SettingConfig SettingConfig { get; set; }
        public virtual ICollection<TagInTest> TagInTests { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<UserInTest> UserInTests { get; set; }
    }
}
